package io.github.goodgoodjm.otter.adapter.postgresql

import io.github.goodgoodjm.otter.core.adapter.ddl.DDLProvider
import io.github.goodgoodjm.otter.core.adapter.model.*

/**
 * PostgreSQL DDL provider implementation
 */
class PostgreSQLDDLProvider : DDLProvider {

    private val typeMapper = PostgreSQLTypeMapper()

    override fun createTable(table: TableDefinition): List<String> {
        val statements = mutableListOf<String>()
        
        // Build CREATE TABLE statement
        val columns = table.columns.joinToString(",\n    ") { column ->
            buildColumnDefinition(column)
        }

        val primaryKeyConstraint = if (table.primaryKeys.isNotEmpty()) {
            ",\n    CONSTRAINT ${table.name}_pkey PRIMARY KEY (${table.primaryKeys.joinToString(", ")})"
        } else ""

        val foreignKeyConstraints = table.foreignKeys.joinToString("") { fk ->
            ",\n    CONSTRAINT ${fk.name} FOREIGN KEY (${fk.columns.joinToString(", ")}) " +
            "REFERENCES ${fk.referencedTable} (${fk.referencedColumns.joinToString(", ")})" +
            buildReferentialActions(fk.onUpdate, fk.onDelete)
        }

        val uniqueConstraints = table.uniqueConstraints.joinToString("") { uc ->
            ",\n    CONSTRAINT ${uc.name} UNIQUE (${uc.columns.joinToString(", ")})"
        }

        val checkConstraints = table.checkConstraints.joinToString("") { cc ->
            ",\n    CONSTRAINT ${cc.name} CHECK (${cc.expression})"
        }

        val schemaPrefix = table.schema?.let { "$it." } ?: ""
        
        statements.add("""
            |CREATE TABLE IF NOT EXISTS $schemaPrefix${table.name} (
            |    $columns$primaryKeyConstraint$foreignKeyConstraints$uniqueConstraints$checkConstraints
            |)""".trimMargin())

        // Add table comment if present
        table.comment?.let {
            statements.add(addTableComment(table.name, it)!!)
        }

        // Add column comments
        table.columns.filter { it.comment != null }.forEach { column ->
            statements.add(addColumnComment(table.name, column.name, column.comment!!)!!)
        }

        // Create indexes
        table.indexes.forEach { index ->
            statements.add(createIndex(table.name, index))
        }

        return statements
    }

    private fun buildColumnDefinition(column: ColumnDefinition): String {
        val type = typeMapper.mapTypeWithModifiers(column.type, column.modifiers)
        
        val notNull = if (ColumnModifier.NOT_NULL in column.modifiers || 
                          ColumnModifier.PRIMARY_KEY in column.modifiers) " NOT NULL" else ""
        
        val unique = if (ColumnModifier.UNIQUE in column.modifiers) " UNIQUE" else ""
        
        val defaultValue = column.defaultValue?.let { 
            " DEFAULT ${typeMapper.getSqlLiteral(it)}" 
        } ?: ""

        val generated = when {
            ColumnModifier.GENERATED_ALWAYS in column.modifiers -> 
                " GENERATED ALWAYS AS IDENTITY"
            ColumnModifier.GENERATED_BY_DEFAULT in column.modifiers -> 
                " GENERATED BY DEFAULT AS IDENTITY"
            else -> ""
        }

        val references = column.references?.let { ref ->
            " REFERENCES ${ref.table}(${ref.column})" +
            buildReferentialActions(ref.onUpdate, ref.onDelete)
        } ?: ""

        return "${column.name} $type$notNull$unique$defaultValue$generated$references"
    }

    private fun buildReferentialActions(onUpdate: ReferentialAction, onDelete: ReferentialAction): String {
        val updateAction = if (onUpdate != ReferentialAction.NO_ACTION) {
            " ON UPDATE ${mapReferentialAction(onUpdate)}"
        } else ""

        val deleteAction = if (onDelete != ReferentialAction.NO_ACTION) {
            " ON DELETE ${mapReferentialAction(onDelete)}"
        } else ""

        return updateAction + deleteAction
    }

    private fun mapReferentialAction(action: ReferentialAction): String {
        return when (action) {
            ReferentialAction.NO_ACTION -> "NO ACTION"
            ReferentialAction.RESTRICT -> "RESTRICT"
            ReferentialAction.CASCADE -> "CASCADE"
            ReferentialAction.SET_NULL -> "SET NULL"
            ReferentialAction.SET_DEFAULT -> "SET DEFAULT"
        }
    }

    override fun alterTable(tableName: String, alterations: List<TableAlteration>): List<String> {
        return alterations.map { alteration ->
            when (alteration) {
                is TableAlteration.AddColumn -> {
                    val columnDef = buildColumnDefinition(alteration.column)
                    "ALTER TABLE $tableName ADD COLUMN $columnDef"
                }
                is TableAlteration.DropColumn -> {
                    val cascade = if (alteration.cascade) " CASCADE" else ""
                    "ALTER TABLE $tableName DROP COLUMN ${alteration.columnName}$cascade"
                }
                is TableAlteration.RenameColumn -> {
                    "ALTER TABLE $tableName RENAME COLUMN ${alteration.oldName} TO ${alteration.newName}"
                }
                is TableAlteration.ModifyColumnType -> {
                    val newType = typeMapper.mapType(alteration.newType)
                    val using = alteration.using?.let { " USING $it" } ?: ""
                    "ALTER TABLE $tableName ALTER COLUMN ${alteration.columnName} TYPE $newType$using"
                }
                is TableAlteration.SetColumnDefault -> {
                    if (alteration.defaultValue == null) {
                        "ALTER TABLE $tableName ALTER COLUMN ${alteration.columnName} DROP DEFAULT"
                    } else {
                        val defaultExpr = typeMapper.getSqlLiteral(alteration.defaultValue)
                        "ALTER TABLE $tableName ALTER COLUMN ${alteration.columnName} SET DEFAULT $defaultExpr"
                    }
                }
                is TableAlteration.SetColumnNotNull -> {
                    if (alteration.notNull) {
                        "ALTER TABLE $tableName ALTER COLUMN ${alteration.columnName} SET NOT NULL"
                    } else {
                        "ALTER TABLE $tableName ALTER COLUMN ${alteration.columnName} DROP NOT NULL"
                    }
                }
                is TableAlteration.AddConstraint -> {
                    buildAddConstraintSql(tableName, alteration.constraint)
                }
                is TableAlteration.DropConstraint -> {
                    val cascade = if (alteration.cascade) " CASCADE" else ""
                    "ALTER TABLE $tableName DROP CONSTRAINT ${alteration.constraintName}$cascade"
                }
                is TableAlteration.AddIndex -> {
                    createIndex(tableName, alteration.index)
                }
                is TableAlteration.DropIndex -> {
                    dropIndex(alteration.indexName)
                }
            }
        }
    }

    private fun buildAddConstraintSql(tableName: String, constraint: Constraint): String {
        return when (constraint) {
            is Constraint.PrimaryKey ->
                "ALTER TABLE $tableName ADD CONSTRAINT ${constraint.name} PRIMARY KEY (${constraint.columns.joinToString(", ")})"
            is Constraint.ForeignKey ->
                "ALTER TABLE $tableName ADD CONSTRAINT ${constraint.name} FOREIGN KEY (${constraint.columns.joinToString(", ")}) " +
                "REFERENCES ${constraint.referencedTable} (${constraint.referencedColumns.joinToString(", ")})" +
                buildReferentialActions(constraint.onUpdate, constraint.onDelete)
            is Constraint.Unique ->
                "ALTER TABLE $tableName ADD CONSTRAINT ${constraint.name} UNIQUE (${constraint.columns.joinToString(", ")})"
            is Constraint.Check ->
                "ALTER TABLE $tableName ADD CONSTRAINT ${constraint.name} CHECK (${constraint.expression})"
        }
    }

    override fun dropTable(tableName: String, cascade: Boolean): String {
        val cascadeClause = if (cascade) " CASCADE" else ""
        return "DROP TABLE IF EXISTS $tableName$cascadeClause"
    }

    override fun createIndex(tableName: String, index: IndexDefinition): String {
        val unique = if (index.unique) "UNIQUE " else ""
        val using = if (index.type != IndexType.BTREE) " USING ${index.type}" else ""
        val where = index.where?.let { " WHERE $it" } ?: ""

        return "CREATE ${unique}INDEX IF NOT EXISTS ${index.name} ON ${tableName}$using (${index.columns.joinToString(", ")})$where"
    }

    override fun dropIndex(indexName: String, tableName: String?): String {
        val cascade = if (tableName != null) " CASCADE" else ""
        return "DROP INDEX IF EXISTS $indexName$cascade"
    }

    override fun addForeignKey(constraint: ForeignKeyConstraint): String {
        return "ALTER TABLE ${constraint.tableName} ADD CONSTRAINT ${constraint.name} " +
               "FOREIGN KEY (${constraint.columns.joinToString(", ")}) " +
               "REFERENCES ${constraint.referencedTable} (${constraint.referencedColumns.joinToString(", ")})" +
               buildReferentialActions(constraint.onUpdate, constraint.onDelete)
    }

    override fun dropForeignKey(constraintName: String, tableName: String): String {
        return "ALTER TABLE $tableName DROP CONSTRAINT $constraintName"
    }

    override fun tableExists(tableName: String, schema: String?): String {
        val schemaCondition = schema?.let { "AND table_schema = '$it'" } ?: "AND table_schema = 'public'"
        return """
            |SELECT EXISTS (
            |    SELECT 1 FROM information_schema.tables 
            |    WHERE table_name = '$tableName' $schemaCondition
            |) AS exists
        """.trimMargin()
    }

    override fun getTableColumns(tableName: String, schema: String?): String {
        val schemaCondition = schema?.let { "AND table_schema = '$it'" } ?: "AND table_schema = 'public'"
        return """
            |SELECT column_name, data_type, is_nullable, column_default
            |FROM information_schema.columns
            |WHERE table_name = '$tableName' $schemaCondition
            |ORDER BY ordinal_position
        """.trimMargin()
    }

    override fun renameTable(oldName: String, newName: String): String {
        return "ALTER TABLE $oldName RENAME TO $newName"
    }

    override fun addColumnComment(tableName: String, columnName: String, comment: String): String {
        return "COMMENT ON COLUMN $tableName.$columnName IS '$comment'"
    }

    override fun addTableComment(tableName: String, comment: String): String {
        return "COMMENT ON TABLE $tableName IS '$comment'"
    }

    override fun alterTableAddColumn(tableName: String, column: ColumnDefinition): String {
        val columnDef = buildColumnDefinition(column)
        return "ALTER TABLE $tableName ADD COLUMN $columnDef"
    }

    override fun alterTableModifyColumn(tableName: String, column: ColumnDefinition): String {
        val type = typeMapper.mapTypeWithModifiers(column.type, column.modifiers)
        val alterStatements = mutableListOf<String>()

        // PostgreSQL requires separate statements for type and constraints
        alterStatements.add("ALTER TABLE $tableName ALTER COLUMN ${column.name} TYPE $type")

        if (ColumnModifier.NOT_NULL in column.modifiers) {
            alterStatements.add("ALTER TABLE $tableName ALTER COLUMN ${column.name} SET NOT NULL")
        } else {
            alterStatements.add("ALTER TABLE $tableName ALTER COLUMN ${column.name} DROP NOT NULL")
        }

        column.defaultValue?.let { default ->
            val defaultStr = when (default) {
                is String -> "'$default'"
                else -> default.toString()
            }
            alterStatements.add("ALTER TABLE $tableName ALTER COLUMN ${column.name} SET DEFAULT $defaultStr")
        }

        return alterStatements.joinToString("; ")
    }

    override fun alterTableDropColumn(tableName: String, columnName: String, cascade: Boolean): String {
        val cascadeClause = if (cascade) " CASCADE" else ""
        return "ALTER TABLE $tableName DROP COLUMN $columnName$cascadeClause"
    }

    override fun alterTableRenameColumn(tableName: String, oldName: String, newName: String): String {
        return "ALTER TABLE $tableName RENAME COLUMN $oldName TO $newName"
    }

    override fun alterTableAddPrimaryKey(tableName: String, columns: List<String>): String {
        val constraintName = "${tableName}_pkey"
        return "ALTER TABLE $tableName ADD CONSTRAINT $constraintName PRIMARY KEY (${columns.joinToString(", ")})"
    }

    override fun alterTableDropPrimaryKey(tableName: String): String {
        val constraintName = "${tableName}_pkey"
        return "ALTER TABLE $tableName DROP CONSTRAINT $constraintName"
    }

    override fun alterTableAddForeignKey(tableName: String, foreignKey: ForeignKeyConstraint): String {
        return addForeignKey(foreignKey)
    }

    override fun alterTableDropForeignKey(tableName: String, constraintName: String): String {
        return dropForeignKey(constraintName, tableName)
    }
}