package io.github.goodgoodjm.otter.core.dsl.altertable

import io.github.goodgoodjm.otter.core.dsl.*
import io.github.goodgoodjm.otter.core.dsl.createtable.ColumnSchema
import org.jetbrains.exposed.sql.transactions.TransactionManager
import org.jetbrains.exposed.sql.vendors.*

class AlterTableContext(val tableSchema: AlterTableSchema) : SchemaContext {
    
    override fun resolve(): List<String> {
        return tableSchema.operations.mapNotNull { operation ->
            when (operation) {
                is AddColumnOperation -> buildAddColumnStatement(operation)
                is ModifyColumnOperation -> buildModifyColumnStatement(operation)
                is DropColumnOperation -> buildDropColumnStatement(operation)
            }
        }
    }
    
    private fun buildAddColumnStatement(op: AddColumnOperation): String? {
        val schema = op.columnSchema ?: return null
        val columnDef = buildColumnDefinition(op.columnName, schema)
        
        val addKeyword = when (getCurrentDialect()) {
            is H2Dialect, is PostgreSQLDialect, is SQLiteDialect -> "ADD COLUMN"
            is MysqlDialect, is MariaDBDialect -> "ADD COLUMN"
            is SQLServerDialect, is OracleDialect -> "ADD"
            else -> "ADD COLUMN"
        }
        
        return "ALTER TABLE ${tableSchema.name} $addKeyword $columnDef"
    }
    
    private fun buildModifyColumnStatement(op: ModifyColumnOperation): String? {
        val schema = op.columnSchema ?: return null
        val columnDef = buildColumnDefinition(op.columnName, schema)
        
        return when (getCurrentDialect()) {
            is MysqlDialect, is MariaDBDialect -> 
                "ALTER TABLE ${tableSchema.name} MODIFY COLUMN $columnDef"
            is PostgreSQLDialect ->
                "ALTER TABLE ${tableSchema.name} ALTER COLUMN ${op.columnName} TYPE ${schema.columnType.sqlType()}"
            is SQLServerDialect ->
                "ALTER TABLE ${tableSchema.name} ALTER COLUMN $columnDef"
            is OracleDialect ->
                "ALTER TABLE ${tableSchema.name} MODIFY $columnDef"
            is H2Dialect ->
                "ALTER TABLE ${tableSchema.name} ALTER COLUMN $columnDef"
            else ->
                "ALTER TABLE ${tableSchema.name} ALTER COLUMN $columnDef"
        }
    }
    
    private fun buildDropColumnStatement(op: DropColumnOperation): String {
        return "ALTER TABLE ${tableSchema.name} DROP COLUMN ${op.columnName}"
    }
    
    private fun getCurrentDialect(): DatabaseDialect {
        return TransactionManager.current().db.dialect
    }
    
    private fun buildColumnDefinition(name: String, schema: ColumnSchema): String {
        val parts = mutableListOf<String>()
        parts.add(name)
        parts.add(schema.columnType.sqlType())
        
        schema.constraints.forEach { constraint ->
            when (constraint) {
                is Constraint.NOT_NULL -> parts.add("NOT NULL")
                is Constraint.UNIQUE -> parts.add("UNIQUE")
                is Constraint.PRIMARY -> parts.add("PRIMARY KEY")
                is Constraint.AUTO_INCREMENT -> parts.add("AUTO_INCREMENT")
                is Constraint.DEFAULT -> {
                    val value = when (constraint.value) {
                        is String -> "'${constraint.value}'"
                        else -> constraint.value.toString()
                    }
                    parts.add("DEFAULT $value")
                }
                is Constraint.CHECK -> parts.add("CHECK (${constraint.condition})")
                is Constraint.COMMENT -> {}
                is Constraint.COLLATE -> parts.add("COLLATE ${constraint.collation}")
                is Constraint.GENERATED -> {
                    val genType = when (constraint.type) {
                        GenerationType.ALWAYS -> "GENERATED ALWAYS AS IDENTITY"
                        GenerationType.BY_DEFAULT -> "GENERATED BY DEFAULT AS IDENTITY"
                    }
                    parts.add(genType)
                }
                is Constraint.REFERENCES -> {}
                else -> {}
            }
        }
        
        schema.foreignKey?.let { fk ->
            parts.add("REFERENCES $fk")
        }
        
        return parts.joinToString(" ")
    }
}